#
# Makefile for the touchscreen drivers.
#

obj-$(CONFIG_TOUCHSCREEN_OPLUS) += util_interface/
obj-$(CONFIG_TOUCHSCREEN_OPLUS) += touchpanel_common_driver.o touchpanel_healthinfo.o touchpanel_exception.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS) += Synaptics/
